feat: add support for multimodal in Vertex
huggingface/chat-ui pull request #1338
Opened 2024-07-10 20:33 UTC by ArthurGoupil

See https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/image-understanding#supported_models

2024-07-11 04:35 UTC, adhishthite commented
@ArthurGoupil This is awesome. Will the same multimodal principles apply for OpenAI endpoints too? I am looking to develop multimodal capability for OpenAI endpoints

2024-07-11 07:46 UTC, ArthurGoupil commented
Hi @adhishthite, I think you can reuse the generic parts of the implementation in https://github.com/huggingface/chat-ui/pull/1021, but the final data structure (with `inlineData`) is specific to Vertex, you should find the good one in OpenAI doc

2024-07-16 09:00 UTC, nsarrazin reviewed
Hi, thanks for the contribution, looks great! 

Would it be possible to also update the docs [here](https://github.com/huggingface/chat-ui/blob/main/docs/source/configuration/models/providers/google.md) to show how we can use multimodal models with vertex ?

Other than that LGTM!

2024-07-17 09:47 UTC, pocman reviewed
Tested locally, it's working, I'm able to upload an image and the model is using it to answer.

2024-07-17 09:47 UTC, pocman commented on README.md
> +          "multimodal": "{
```suggestion
          "multimodal": {
```

2024-07-17 09:47 UTC, pocman commented on README.md
> +          }"
```suggestion
          }
```

2024-07-17 09:47 UTC, pocman commented on README.md
> +              "maxHeight": number;
```suggestion
              "maxHeight": 1000;
```

2024-07-17 09:47 UTC, pocman commented on README.md
>            "tools": [{
grounding is not supported with multimodal yet.
So tools or multimodal are mutualy exclusive

2024-07-17 09:47 UTC, pocman commented on README.md
> +          "model": {
This is not used, root name and id are used.

2024-07-17 09:47 UTC, pocman commented on src/lib/server/endpoints/google/endpointVertex.ts
> +			model: model.name ?? model.id,
revert to model.id ?? model.name, until the nested model object is actually used.

2024-07-29 07:41 UTC, nsarrazin commented
Hi @ArthurGoupil, I'm not super familiar with the vertex endpoint but wdyt of the comments on the review from @pocman ? Feel free to approve or not and then I'll merge this :smile:

2024-07-29 12:21 UTC, ArthurGoupil commented
Hi @nsarrazin, yeah i need to apply them once i have some time, probably in september :/

2024-09-05 12:48 UTC, pocman approved these changes

2024-09-05 13:03 UTC, pocman requested changes

2024-09-05 13:03 UTC, pocman commented on src/lib/server/endpoints/google/endpointVertex.ts
> +			tools: !multimodal ? tools : undefined,
condition should not be on !multimodal but on files.length == 0

2024-09-09 12:34 UTC, pocman commented
@nsarrazin I believe this is ready to be merged. Can you have a look ?

2024-09-09 12:58 UTC, merged