Support in message latex rendering and latex block
huggingface/chat-ui pull request #416
Opened 2023-08-27 22:27 UTC by theblackcat102

Added support for in message latex and rendering of latex code block

2023-08-28 17:46 UTC, julien-c commented
see https://github.com/huggingface/chat-ui/issues/257 btw

2023-08-30 08:14 UTC, nsarrazin requested changes
Hi! Thanks for the contribution. I think this would be a great addition, I appreciate you tackling it. 

I added a few comments, please have a look when you have the time :smile:

2023-08-30 08:14 UTC, nsarrazin commented on src/lib/components/LatexBlock.svelte
> +        document.head.append(script);
Is there a reason why this can't just be added as a dependency with npm ?

2023-08-30 08:14 UTC, nsarrazin commented on src/lib/components/LatexBlock.svelte
> +	<!-- eslint-disable svelte/no-at-html-tags -->
Why do you disable eslint for this line if you're not using `@html` afterwards ?

2023-08-30 08:14 UTC, nsarrazin commented on src/lib/components/chat/ChatMessage.svelte
> +	import "../../../styles/latex.css";
Styles can be added directly in a [sveltekit component](https://learn.svelte.dev/tutorial/styling) if needed using the `<style></style>` markup. 

This is more consistent with the way we do styling elsewhere in the app :grin:

2023-08-30 08:14 UTC, nsarrazin commented on src/lib/components/chat/ChatMessage.svelte
> +			}
Same comment as above, could this be done by adding a dependency instead ?

2023-09-08 16:32 UTC, julien-c reviewed
contribution looks really cool @theblackcat102, we would love to merge it! 🔥

let us know if you would like some help getting it over the finish line.

cc @gary149

2023-09-20 12:07 UTC, nsarrazin commented
Closing this PR since we just merged #450 !

2023-09-20 12:07 UTC, closed without merging